### PR TITLE
Basic admin page allowing to delete pastes

### PR DESCRIPTION
**Pull request by Shir0kamii**

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
Reviewed, just some code style issues!

**Comment by Shir0kamii** [comment]
@RaitoBezarius: Please don't forget to review this code too.

I choosed to use an id, because using btn-primary would hinder me when clicking the button on the admin page.

**Comment by RaitoBezarius** [comment]
On Tue, Sep 15, 2015 at 05:51:35PM -0700, Shir0kamii wrote:
>    [1]@RaitoBezarius: Please don't forget to review this code too.
> 
>    I choosed to use an id, because using btn-primary would hinder me when
>    clicking the button on the admin page.
CSS selectors wouldn't do it? (CSS selectors are cleaner imo, but you
can use an id if we take in account that the admin area is "small")

**Comment by Shir0kamii** [comment]
what kind of selector would you make ?

**Pull request merged**
